# Generated by Django 5.1.1 on 2024-10-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('source_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_files', models.IntegerField()),
                ('total_uncategories', models.IntegerField()),
                ('total_large_file', models.IntegerField()),
                ('total_miss_nip', models.IntegerField()),
                ('total_not_a_pdf', models.IntegerField()),
                ('total_doc_proceed', models.IntegerField()),
                ('total_doc_uploaded', models.IntegerField()),
            ],
        ),
    ]
