# Generated by Django 5.1.2 on 2024-10-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanmonitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ananda', models.IntegerField()),
                ('bagas', models.IntegerField()),
                ('nia', models.IntegerField()),
                ('nathan', models.IntegerField()),
            ],
        ),
    ]
