# Generated by Django 5.1.2 on 2024-10-10 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanmonitoring', '0003_monitoringpersonal_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoringpersonal',
            old_name='timestamp',
            new_name='jedawaktu',
        ),
    ]
